### ISSUE TITLE
Restore compression header parameter

### ISSUE THREAD

**Issue by selfissued** [cose-wg/cose-issues#22]
Please restore the “zip” header parameter definition.  Having a standard way to compress the plaintext before encryption is an important capability.  I didn’t see a compelling motivation for its removal when it was briefly discussed on the mailing list.

**Comment by LudwigSeitz** [comment]
I am not in favour of having this parameter in the COSE spec. The reason is that I suspect it will not be used very much in the constrained space, and if this parameter can be part  of a message, I have to implement code on my constrained device to handle it.
Keep in mind that we are dealing with devices that can have as little as 100 KB of flash memory for code libraries and other persistent data (See Class 1, Section 3 RFC 7228).

**Comment by jimsch** [comment]
CRIME has demonstrated that we do not understand how to do generic compression.  This means that compression needs to be an application specified feature and not a security feature.  This is a strong justification for removal of compression from COSE.

**Comment by cose-ietf** [comment]
Hi Ludwig

Is this also true based on yesterday's presentation where it was mentioned that communication is orders of magnitude more energy than computation. I doubt there is anything to compress o on an already efficient encoding but will not completely dismiss its need in the constrained space.

Sandeep

**Comment by cabo** [comment]
I'm sympathetic with Ludwig's point, however, it should be the prerogative of the enclosing media type to define whether decompression capability is expected or not.
(Also, we have to be careful about equating compression with deflate.  There are other schemes that are more appropriate for decompression on constrained devices.)

**Comment by selfissued** [comment]
The CRIME argument is persuasive.  I'm willing to drop this request on that basis.  Thanks to all who discussed the possibility.
