### ISSUE TITLE
add the value type 'bstr' to counter signature

### ISSUE THREAD

**Issue by fpalombini** [cose-wg/cose-issues#52]
We propose to give the choice between the whole COSE_Signature structure or only the bstr 'signature' as "counter signature" value type. In CDDL, that would give:

 Generic_Headers = (
    ...
    ? 7 => COSE_Signature / bstr, ; Counter signature
    ...
)

on section 3.1 and in Table 2.
If we only send the btstr 'signature', we assume that the alg for the counter signature is also pre-established between nodes and is included in the "alg" parameter.

**Comment by jimsch** [comment]
Per discussion on the list, this has been changed from a request to modify the current existing counter signature attribute to defining a new one.  The reason for the change in the request is that the input for the new counter signature computation process should reflect the ToBeSigned structure of the COSE_Sign1 rather than the full COSE_Sign structure.  This better reflects the circumstances that it is being designed for.

**Comment by selfissued** [comment]
It's not clear to me why another way of doing this is being requested.  Are both really needed?

**Comment by fpalombini** [comment]
Hi Mike, the goal behind this is again to reduce the size of the COSE message: instead of using a COSE_Signature structure (which itself contains headers and bstr signature value), we would like to use the simple bstr signature value directly.  This would reduce the size of 3B: 1 for the array, 1 for the unprotected header and 1 for the protected header.

(the discussion about this in the mailing list is [here]([COSE] Issue - add the value type 'bstr' to counter signature)).
